### ISSUE TITLE
type' object is not subscriptable 

### ISSUE THREAD

**Issue by nehatkkhan786** [Kh4lidMD/AlAdhan#2]
Why I am getting this error while running the code. 
```

import aladhan

location = aladhan.City("Doha", "QA") # Doha, Qatar
client = aladhan.Client(location)

adhans = client.get_today_times()

print("Today's Prayer Times for Doha, Qatar")
print("======================================")
for adhan in adhans:
    print("{: <15} | {: <15}".format(adhan.get_en_name(), adhan.readable_timing(show_date=False)))
```

I tried to run this documentation code but I am getting "'type' object is not subscriptable"
 The full Error 
```

Traceback (most recent call last):
  File "adhan.py", line 1, in <module>
    import aladhan
  File "/Users/abdulrasid/Desktop/Devs/PythonScripts/Ajaan/venv/lib/python3.8/site-packages/aladhan/__init__.py", line 1, in <module>
    from .client import Client
  File "/Users/abdulrasid/Desktop/Devs/PythonScripts/Ajaan/venv/lib/python3.8/site-packages/aladhan/client.py", line 13, in <module>
    class Client:
  File "/Users/abdulrasid/Desktop/Devs/PythonScripts/Ajaan/venv/lib/python3.8/site-packages/aladhan/client.py", line 65, in Client
    ) -> list[Adhan]:
TypeError: 'type' object is not subscriptable
 
```

**Comment by Kh4lidMD** [comment]
Please update the package and try to run the code on your machine not on some API runner website because it's possible it is not working because of that, and check if Aladhan API is up at the time you ran the code.

There will be a beta version soon Inshallah with more features that will be built from scratch.
